(function(){'use strict';var g={l:function(a,b,c){if("undefined"!=typeof c){var d=g.c();d&&d.saveStyleOverride(a,b,c);a.style[b]=c}},f:function(a,b,c){c?a.classList.add(b):a.classList.remove(b)},w:function(a,b){if("undefined"!=typeof b){var c=g.c();c&&c.saveInitialText(a);a.textContent=b;c&&c.applyStylePreservation(a)}},v:function(a,b){if("undefined"!=typeof b){var c=g.c();c&&c.saveInitialText(a);a.innerHTML=b;c&&c.applyStylePreservation(a)}},show:function(a,b){a.style.display=!b||"string"==typeof b&&"false"==b.toLowerCase()?
"none":""},setAttribute:function(a,b,c){"undefined"!=typeof c&&a.setAttribute(b,c)},c:function(){return document.querySelector("gwd-text-helper")}};window.Binder=g;g.setText=g.w;g.setStyle=g.l;g.setHtml=g.v;g.addOrRemoveClassName=g.f;g.show=g.show;g.setAttribute=g.setAttribute;var h=function(a,b){if(a&&Array.isArray(a)){var c=b?b.split("."):[""];return a.map(function(d){if(1==c.length)return d[c[0]];var e=d;c.forEach(function(f){e&&(e=e[f])});return e})}return[]},l=function(a,b){return a&&Array.isArray(a)?a.join(b||","):""},m={hex:function(a){return a?a.replace(/0x/,"#"):a},limit:function(a,b){return b?a&&Array.isArray(a)&&("string"==typeof b&&(b=parseInt(b,10)),!isNaN(b))?a.slice(0,b):a:a},lowercase:function(a){return a?a.toLowerCase():a}};m.join=l;
m.pixelvalue=function(a){if("undefined"!=typeof a)return a+"px"};m.pluck=h;m.pluckandjoin=function(a,b){return l(h(a,b))};m.uppercase=function(a){return a?a.toUpperCase():a};var p=function(a,b,c){if(c){var d=document.createEvent("CustomEvent");d.initCustomEvent(a,!0,!0,c)}else d=document.createEvent("Event"),d.initEvent(a,!0,!0);b.dispatchEvent(d)};var q=function(a,b){a=a.split(".");for(var c=window,d=0;c&&d<a.length;d++)c=c[a[d]];if(c&&"function"===typeof c[b])return c[b]};var r=/^bind-/,t=/^style-/,u=/^class-/,v=/^each-/,w=/-([a-z])/g;function x(a){return String(a).replace(w,function(b,c){return c.toUpperCase()})}function y(a){return!(!a||!r.test(a.name))}function z(a){return!(!a||0!=a.name.indexOf("bind-each"))}function A(a){Array.prototype.slice.call(a.attributes).filter(z).forEach(function(b){a.removeAttribute(b.name)})}var B=function(){};goog.inherits(B,HTMLElement);
B.prototype.createdCallback=function(){this.b={text:"setText",html:"setHtml",show:"show"};this.j=!1;this.a=null;this.h=this.u.bind(this)};B.prototype.detachedCallback=function(){C(this)};
B.prototype.bindData=function(a,b){b=b||Array.prototype.slice.call(this.ownerDocument.querySelectorAll("*"));var c=(c=this.ownerDocument.querySelector("meta[name=environment]"))?c.getAttribute("content"):"";this.j="gwd-adwords"==c||"gwd-googleads"==c;C(this);(this.a=this.ownerDocument.querySelector("gwd-font-loader"))&&this.a.startDynamicFontLoading();b.forEach(this.g.bind(this,a));a=!0;this.a&&((a=this.a.endDynamicFontLoading())||this.a.addEventListener("gwdfontsloaded",this.h));return a};
B.prototype.g=function(a,b){if(!b.hasAttribute("gwd-bind-each-template")){for(var c,d=Array.prototype.slice.call(b.attributes),e=d.length,f=0;f<e;f++)if(z(d[f])){c=d[f];break}a=this.o.bind(this,b,a);c?a(c):d.filter(y).forEach(a)}};
B.prototype.o=function(a,b,c){var d=c.name,e=d.replace(r,"");if(t.test(e)){var f=e.replace(t,"");f=g.l.bind(null,a,x(f))}else u.test(e)?(f=e.replace(u,""),f=g.f.bind(null,a,f)):v.test(e)?(f=e.replace(v,""),f=this.m.bind(this,a,f,b)):f=this.b[e]&&"function"==typeof g[this.b[e]]?g[this.b[e]].bind(null,a):q("gwd.binders",e)||g.setAttribute.bind(null,a,e);d=a.getAttribute(d);b=(-1!==d.indexOf("|")?this.s.bind(this,b,d):this.i.bind(this,b,d)).call(a);"style-font-family"==e&&this.a&&(b=this.a.parseFontList(b));
"exit-override-url"==e&&(e=(e=c.value)&&e.match(/product\.\d+/i)?(e=e.match(/product\.(\d+)/i))&&e[1]?parseInt(e[1],10):null:null,null!=e&&a.setAttribute("product-index",e),this.j&&a.setAttribute("exit-id",c.value.replace(/\./g,"_")));f.apply(a,[b])};
B.prototype.m=function(a,b,c,d){var e=a.parentNode;if(e){var f=a.cloneNode(!0);A(f);for(var n=[],k=0;d&&k<d.length;k++)n.push(f.cloneNode(!0));p("gwdbindeachcloned",a,{instances:n});f=this.ownerDocument.createComment("gwd-bind-each-placeholder");e.insertBefore(f,a);e.removeChild(a);D(a);if(d&&0!=d.length){for(k=0;k<d.length;k++)c[b]=d[k],a=n[k],a.setAttribute("gwd-repeat-index",k),c.$index=k,Array.prototype.slice.call(a.querySelectorAll("*")).concat(a).forEach(this.g.bind(this,c)),e.insertBefore(a,
f);delete c[b]}}};var D=function(a){a.setAttribute("gwd-bind-each-template","");Array.prototype.slice.call(a.querySelectorAll("*")).forEach(function(b){b.setAttribute("gwd-bind-each-template","")})};B.prototype.i=function(a,b){if(a){if(b){b=b.replace("[",".");b=b.replace("]","");var c=a;b.split(".").forEach(function(d){c&&(c=c[d])});return c}return a}};
B.prototype.s=function(a,b){if(!b)return a;b=b.split("|");var c=b.shift().trim();a=this.i(a,c);if("undefined"!=typeof a){for(c=0;c<b.length;c++)a=E(this,a,b[c].trim());return a}};var E=function(a,b,c){c=c.split(" ").map(function(f){return f.trim()});var d=c.shift(),e=m[d];c.unshift(b);return e?e.apply(null,c):(d=q("gwd.formatters",d))?d.apply(a,c):b};B.prototype.u=function(){C(this);p("bindingfinished",this)};var C=function(a){a.a&&(a.a.removeEventListener("gwdfontsloaded",a.h),a.a=null)};
document.registerElement("gwd-data-binder",{prototype:B.prototype});}).call(this);
