(function(){var f,l=function(a,b,c){a=parseInt(a.getAttribute(b),10);isNaN(a)&&(a=c);return a},m=function(a,b,c){a=parseFloat(a.getAttribute(b));isFinite(a)||(a=c);return a};var p=function(a){return"gwd-page"==a.tagName.toLowerCase()||"gwd-page"==a.getAttribute("is")},aa=function(a){if(p(a))return a;for(;a&&9!=a.nodeType;)if((a=a.parentElement)&&p(a))return a;return null},q=function(a,b,c,d){d=d||b;a.hasAttribute(b)?(a=a.getAttribute(b),c.setAttribute(d,a)):c.removeAttribute(d)};var x=function(a,b){function c(){}c.prototype=b.prototype;a.G=b.prototype;a.prototype=new c;a.prototype.constructor=a};var y=["-ms-","-moz-","-webkit-",""],z=function(a,b,c){for(var d,e,h=0;h<y.length;++h)d=y[h]+b,e=""+c,a.style.setProperty(d,e)};var C=function(a,b,c){if(c){var d=document.createEvent("CustomEvent");d.initCustomEvent(a,!0,!0,c)}else d=document.createEvent("Event"),d.initEvent(a,!0,!0);b.dispatchEvent(d);return d},ba=function(a,b){setTimeout(function(){C("autoplayended",a,b)},0)},ca=function(a,b){var c=function(d){a.removeEventListener("attached",c);b(d)};a.addEventListener("attached",c)};var da=function(a){a=a.trim();return window.Enabler?Enabler.getUrl(a):a};var ea=function(a){var b=a.currentIndex-1;return b-b%a.frameSnapInterval},D=function(a){this.l=a;this.v=null;this.Fa=!0;this.N=!1};
D.prototype.play=function(a,b,c){if(this.l.frameCount&&null==this.v){b=b||"forwards";if(c){var d=Math.floor(a/c);a=c}else d=this.l.frameCount,a/=d;var e=[],h=ea(this.l);c=h;for(var k=0;k<d;k++){if(0<k||!this.Fa)c=E(c+F(b,1),this.l.frameCount);e.push(c)}b=function(){if(e.length){var g=e.shift();this.N=!0;this.l.goToFrame(g+1);this.N=!1;var n=this.l;C("frameautoplayed",n,{id:g+1||n.currentIndex})}else this.stop(!0),this.l.goToFrame(h+1)}.bind(this);this.v=setInterval(b,a);setTimeout(b)}};
D.prototype.stop=function(a){!this.N&&this.v&&(clearInterval(this.v),ba(this.l,{completed:!!a}),this.v=null)};
var fa=function(a){var b=document.createElement("gwd-image");b.setAttribute("source",a);return b},H=function(a){var b=[];if(a){a=a.split(",");for(var c=0;c<a.length;++c)/\S/.test(a[c])&&b.push(fa(da(a[c])))}return b},I=function(a,b){for(var c=0,d=a.length;c<d;c++){var e=a[c];if("img"==e.tagName.toLowerCase()&&"gwd-image"==e.getAttribute("is")||"gwd-image"==e.tagName.toLowerCase())null!=b?e.setAttribute("scaling",b):e.removeAttribute("scaling")}},ha=function(a,b){var c=b.length;b=b.splice(0,c);for(var d,
e=0;e<c;e++)d=b[e],"frameshown"==d?C(d,a,{id:a.currentIndex}):C(d,a)},F=function(a,b){return"left"==a||"backwards"==a?-b:b},E=function(a,b){return(a%b+b)%b},ia=function(a){Array.prototype.slice.call(a.querySelectorAll("video, gwd-youtube, audio,gwd-video,gwd-audio")).forEach(function(b){b.pause()})},ja=function(a){Array.prototype.slice.call(a.querySelectorAll("video, gwd-youtube, audio,gwd-video,gwd-audio")).forEach(function(b){b.play()})};var K=function(){};x(K,HTMLElement);f=K.prototype;f.createdCallback=function(){this.frames=[];this.a=null;this.b=0;this.j=1;this.A=new D(this);Object.defineProperty(this,"currentIndex",{enumerable:!0,get:this.oa.bind(this)});Object.defineProperty(this,"frameSnapInterval",{enumerable:!0,get:this.ra.bind(this)});Object.defineProperty(this,"frameCount",{enumerable:!0,get:this.qa.bind(this)});this.ga=this.hasAttribute("pause-front-media");this.ha=this.hasAttribute("resume-next-media")};
f.attributeChangedCallback=function(a){switch(a){case "pause-front-media":this.ga=this.hasAttribute("pause-front-media");break;case "resume-next-media":this.ha=this.hasAttribute("resume-next-media")}};f.getFrame=function(a){if(0!=this.b)return this.frames[a-1]};f.gwdLoad=function(){};f.gwdIsLoaded=function(){return!0};f.goToFrame=function(a,b){this.stopRotation();0!=this.b&&(a>this.b?a=this.b:1>a&&(a=1),this.Z(a,b))};f.Z=function(a){this.a=a-1};
var L=function(a,b,c,d){if(null!=a.a){var e=E(a.a+F(b,a.j||1),a.j*Math.ceil(a.b/a.j));null!=d&&!d&&("forwards"==b&&e<a.a||"backwards"==b&&e>a.a)||a.goToFrame(e+1,c||"slide")}};f=K.prototype;f.goBackwards=function(a,b){return L(this,"backwards",a,b)};f.goForwards=function(a,b){return L(this,"forwards",a,b)};f.rotateOnce=function(a,b){this.A.play(a||0,b)};f.stopRotation=function(){this.A.stop()};f.oa=function(){return 0<this.b?this.a+1:void 0};f.ra=function(){return this.j};f.qa=function(){return this.b};var M=function(a,b){return a.x*b.x+a.y*b.y},O=function(a,b){return N(b,M(a,b))},N=function(a,b){return P(a.x*b,a.y*b)},P=function(a,b){return{x:a,y:void 0!==b?b:a}};var Q=function(){};x(Q,K);
Q.prototype.createdCallback=function(){Q.G.createdCallback.call(this);this.O=!1;this.P=this.c=null;if(this.Y=this.hasAttribute("images"))for(;this.firstChild;)this.removeChild(this.firstChild);this.s=P(0);var a=document.createElement("gwd-gesture");a.className="gesture";this.C=a;this.i=!1;this.g=null;this.ca=this.ya.bind(this);this.ea=this.Aa.bind(this);this.aa=this.wa.bind(this);this.ba=this.xa.bind(this);this.da=this.za.bind(this);this.V=this.ta.bind(this);this.na=this.Da.bind(this);this.ma=this.Ca.bind(this);
this.la=this.Ba.bind(this);this.X=this.ua.bind(this);this.fa=this.va.bind(this);this.K=C.bind(null,"firstinteraction",this);this.R=!1;this.D=[];this.w=ha.bind(null,this,this.D);this.ja=this.ka=this.I=this.T=this.S=0;this.M=1;this.J=[];this.L=0;this.ia=1;this.Ea=.7;this.F=0;this.H=!1;this.u=P(0);this.o=P(0);this.h=null;this.m=this.$=-1;this.W=[];this.B=P(-1,-1);a="y"==this.getAttribute("swipe-axis");this.f=P(a?0:1,a?1:0);Object.defineProperty(this,"firstVisibleFrameIndex",{enumerable:!0,get:this.pa.bind(this)});
Object.defineProperty(this,"lastVisibleFrameIndex",{enumerable:!0,get:this.sa.bind(this)})};
Q.prototype.attachedCallback=function(){var a=this.C;a.addEventListener("pointerover",this.ea,!1);a.addEventListener("pointerout",this.ca,!1);a.addEventListener("pointermove",this.aa,!1);a.addEventListener("track",this.na,!1);a.addEventListener("trackend",this.ma,!1);a.addEventListener("tap",this.la,!1);this.addEventListener("frametap",this.X,!1);this.addEventListener("swipefinished",this.U,!1);this.addEventListener("transitionend",this.w,!1);this.addEventListener("webkitTransitionEnd",this.w,!1);
if("function"==typeof this.gwdLoad&&"function"==typeof this.gwdIsLoaded&&!this.gwdIsLoaded()){var b=(a=aa(this))&&"function"==typeof a.gwdIsLoaded;(!a||b&&a.gwdIsLoaded())&&this.gwdLoad()}};
Q.prototype.detachedCallback=function(){var a=this.C;a.removeEventListener("pointerover",this.ea,!1);a.removeEventListener("pointerout",this.ca,!1);a.removeEventListener("pointermove",this.aa,!1);a.removeEventListener("track",this.na,!1);a.removeEventListener("trackend",this.ma,!1);a.removeEventListener("tap",this.la,!1);this.removeEventListener("frametap",this.X,!1);this.removeEventListener("swipefinished",this.U,!1);this.removeEventListener("transitionend",this.w);this.removeEventListener("webkitTransitionEnd",
this.w)};
Q.prototype.attributeChangedCallback=function(a){Q.G.attributeChangedCallback.call(this,a);switch(a){case "images":this.frames=H(this.getAttribute("images"));R(this);S(this);break;case "scaling":I(this.frames,this.getAttribute("scaling"));break;case "has-navigation":case "navigation-highlight":case "navigation-thumbnails":T(this);S(this);break;case "transition-duration":case "exit-urls":case "autoplay-duration":case "autoplay-step-interval":U(this);break;case "frame-width":case "frame-height":case "frame-snap-interval":case "num-frames-to-display":U(this);S(this);
break;case "disable-gesture":case "offset":case "start-frame":case "swipe-threshold-ratio":case "swipe-committed-threshold-ratio":S(this)}};
var U=function(a){var b=l(a,"num-frames-to-display",1),c=l(a,"frame-snap-interval",1),d=l(a,"transition-duration",600),e=l(a,"frame-width",-1),h=l(a,"frame-height",-1),k=m(a,"autoplay-duration",3E3),g=m(a,"autoplay-step-interval",0);a.B.x=e;a.B.y=h;-1!=M(a.B,a.f)?b=-1:0<b&&c>b&&(c=b);e=[];if(h=a.hasAttribute("exit-urls")?a.getAttribute("exit-urls"):""){h=h.split(",");for(var n=0;n<h.length;n++)e[n]=h[n].trim()}a.W=e;a.m=b;a.j=c;a.I=d;a.S=k;a.T=g},S=function(a){var b=P(a.clientWidth,a.clientHeight);
a.h&&(b.y-=36,a.P.style.height=b.y+"px");var c=m(a,"swipe-threshold-ratio",.1),d=m(a,"swipe-committed-threshold-ratio",.5),e=a.f,h=a.m,k=a.B,g=a.frames,n=parseInt(a.getAttribute("offset"),10);isNaN(n)&&(n=0);n=N(e,n);k=P(-1==k.x?b.x:k.x,-1==k.y?b.y:k.y);if(a.hasAttribute("offset")){a:{var t=k.x,r=k.y,A=!0;if(a.hasAttribute("clamp-frame-size-to-image")){var v=a.getAttribute("clamp-frame-size-to-image");"true"==v?A=!0:"false"==v&&(A=!1)}if(A)if(v=a.hasAttribute("scaling")?a.getAttribute("scaling"):
"contain",(A="contain"==v)||"none"==v)if(0==t||0==r)g={width:t,height:r};else{for(var G=v=-1,ka=g.length,J=0;J<ka;J++){var u=g[J];if("img"!=u.tagName.toLowerCase()&&"gwd-image"!=u.tagName.toLowerCase()){g={width:t,height:r};break a}var w=u.assetWidth?u.assetWidth:u.naturalWidth,B=u.assetHeight?u.assetHeight:u.naturalHeight;0<w&&0<B&&(A?w/B<t/r?(u=w/B*r,w=r):(u=t,w=B/w*t):(u=w,w=B),v=Math.max(v,u),G=Math.max(G,w))}g={width:-1!=v?Math.min(t,v):t,height:-1!=G?Math.min(r,G):r}}else g={width:t,height:r};
else g={width:t,height:r}}1==e.x?k.x=g.width:k.y=g.height}1<h&&(g=N(e,h-1),g=P(g.x*n.x,g.y*n.y),g=O(P((b.x-g.x)/h,(b.y-g.y)/h),e),g.x&&(k.x=g.x),g.y&&(k.y=g.y));g=2<h?1+Math.ceil(h/2-1):1;t=parseInt(a.getAttribute("start-frame"),10);isNaN(t)&&(t=g);g=O(P(k.x+n.x,k.y+n.y),e);r=1+2*Math.floor((M(e,b)-M(e,k))/(2*M(e,g)));if(1>r||!isFinite(r))r=1;b=P((b.x-k.x)/2,(b.y-k.y)/2);0<h&&0==h%2&&(e=O(P(k.x+n.x,k.y+n.y),e),b.x-=.5*e.x,b.y-=.5*e.y,r+=1);e=a.hasAttribute("disable-gesture");a.o=k;a.u=b;a.M=r;a.F=
M(g,a.f);a.ia=t;a.i=e;a.ka=M(a.o,a.f)*c;a.ja=M(a.o,a.f)*d;c=O(a.u,P(a.f.y,a.f.x));for(e=0;e<a.b;e++)d=a.frames[e].style,d.left=c.x+"px",d.top=c.y+"px",d.width=a.o.x+"px",d.height=a.o.y+"px",c.x+=g.x,c.y+=g.y;a.s=P(0);a.c&&(V(a,0,0,0),c=O(a.u,a.f),a.c.style.left=c.x+"px",a.c.style.top=c.y+"px");a.a=null;a.goToFrame(a.ia,"none")};f=Q.prototype;f.gwdIsLoaded=function(){return this.O};
f.gwdLoad=function(){if(!this.O&&!this.c){if(this.Y)var a=H(this.getAttribute("images"));else{a=this.childNodes;for(var b=[],c=0,d=a.length;c<d;c++){var e=a[c];e.nodeType==Node.ELEMENT_NODE&&b.push(e)}a=b}this.frames=a;R(this)}};f.goBackwards=function(a,b){return Q.G.goBackwards.call(this,a,null!=b?b:!1)};f.goForwards=function(a,b){return Q.G.goForwards.call(this,a,null!=b?b:!1)};
f.Z=function(a,b){var c=this.j,d=this.b;var e=this.m;--a;a=a-a%c+Math.floor((c-1)/2);0>a?a=0:a>=d&&(a=d-1);1<e&&(c=a-Math.floor((e-1)/2),e=c+e-1,0>c&&e<d-1&&(a+=Math.min(-c,d-e-1)),e>=d&&0<c&&(a-=Math.min(e-d+1,c)));e=a;null!=this.a&&this.a!=e&&(this.ga&&ia(this.frames[this.a]),this.ha&&ja(this.frames[e]));d=this.a;this.a=e;e=N(this.f,-this.F*this.a);V(this,"none"!=b?this.I:0,e.x,e.y);this.s=e;if(this.L)for(b=Math.floor((this.M-1)/2),e=0;e<this.M;e++)if(a=this.a-b+e,!(0>a||a>=this.b||this.J[a]||(this.J[a]=
!0,--this.L))){this.D.push("allframesviewed");break}d!=this.a&&(W(this,this.a+1),this.D.push("frameshown"),this.D.push("swipefinished"));this.R||this.w()};
var V=function(a,b,c,d){a.R=0<b;z(a.c,"transition","transform "+b+"ms");z(a.c,"transform","translate3d("+c+"px,"+d+"px,0)")},R=function(a){for(;a.firstChild;)a.removeChild(a.firstChild);a.h=null;a.c&&(a.c.removeEventListener("pageload",a.fa,!1),a.c.removeEventListener("mouseover",a.da,!0),a.c.removeEventListener("mouseout",a.ba,!0),a.c.removeEventListener("click",a.V,!0));for(var b=a.frames,c=document.createElement("gwd-page"),d,e=0;e<b.length;++e)d=b[e],z(d,"user-select","none"),d.classList.add("frame"),
c.appendChild(d);ca(c,c.gwdLoad.bind(c));a.c=c;c.className="container";a.c.addEventListener("pageload",a.fa,!1);a.c.addEventListener("mouseover",a.da,!0);a.c.addEventListener("mouseout",a.ba,!0);a.c.addEventListener("click",a.V,!0);I(a.frames,a.getAttribute("scaling"));a.b=a.frames.length;b=document.createElement("div");a.P=b;b.className="matte";b.appendChild(c);a.appendChild(a.P);a.appendChild(a.C)};Q.prototype.U=function(){z(this.c,"transition","transform 0ms")};
Q.prototype.va=function(a){a.target===this.c&&(this.O=!0,this.L=this.b,this.J=[],U(this),T(this),S(this),C("allframesloaded",this),this.hasAttribute("autoplay")&&this.A.play(this.S,"forwards",this.T),C("ready",this))};Q.prototype.rotateOnce=function(a,b){this.A.play(a||this.I,b)};
var Y=function(a,b){var c=a.b;if(c){var d=a.a;b=X(a,b);a.goToFrame(b+1);d!=b&&(0==b?C("reachleftend",a):b==c-1&&C("reachrightend",a))}},T=function(a){var b=a.hasAttribute("has-navigation"),c=!!a.h;b&&!c?(b=a.id||a.getAttribute("data-gwd-grp-id"),a.h=document.createElement("gwd-gallerynavigation"),a.h.setAttribute("for",b),a.classList.add("has-navigation"),a.appendChild(a.h)):!b&&c&&(a.classList.remove("has-navigation"),a.removeChild(a.h),a.h=null);a.h&&(q(a,"navigation-highlight",a.h,"highlight"),
q(a,"navigation-thumbnails",a.h,"use-thumbnails"))},X=function(a,b){var c=a.a;Math.abs(b)>a.ka&&(c=0>b?c+a.j:c-a.j);0>c?c=0:c>=a.b&&(c=a.b-1);return c},W=function(a,b){a.$!=b&&(a.$=b,C("frameactivated",a,{id:b||a.currentIndex}))};
Q.prototype.Da=function(a){if(!this.i&&(this.K&&(this.K(),this.K=null),!this.H))if(this.stopRotation(),a=M(P(a.dx,a.dy),this.f),W(this,X(this,a)+1),Math.abs(a)>this.ja)Y(this,a),this.H=!0;else{if(0<a&&0===this.a||0>a&&this.a===this.b-1)a-=a*this.Ea;V(this,0,this.s.x+this.f.x*a,this.s.y+this.f.y*a)}};Q.prototype.Ca=function(a){this.i||(this.H?this.H=!1:Y(this,M(P(a.dx,a.dy),this.f)))};
var Z=function(a,b){var c=a.getBoundingClientRect();b=P(b.clientX-c.left,b.clientY-c.top);c=a.f;var d=P(c.y,c.x);c=M(d,b);var e=M(d,a.u);d=M(d,a.o);if(c<e||c>e+d)return null;c=a.f;b=M(c,b)-M(c,a.s)-M(c,a.u);c=Math.floor(b/a.F);return 0>c||c>=a.b||b%a.F>M(a.f,a.o)?null:c};f=Q.prototype;
f.Ba=function(a){if(!this.i){this.stopRotation();var b=this.C;var c=this.c;var d=a.clientX,e=a.clientY,h=b.style["pointer-events"];b.style["pointer-events"]="none";d=c.ownerDocument.elementFromPoint(d,e);b.style["pointer-events"]=h;if(b=d)if(b=d,c.contains&&1==b.nodeType)b=c==b||c.contains(b);else if("undefined"!=typeof c.compareDocumentPosition)b=c==b||!!(c.compareDocumentPosition(b)&16);else{for(;b&&c!=b;)b=b.parentNode;b=b==c}c=b?d:null;(b=!c)||(b=a.clientX,h=a.clientY,d=!1,"gwd-taparea"===c.tagName.toLowerCase()&&
(d=c.ownerDocument.createEvent("Event"),d.initEvent("action",!0,!0),d.clientX=b,d.clientY=h,d=!c.dispatchEvent(d)),b=!d);b&&(a=Z(this,a),null!=a&&C("frametap",this,{element:this.frames[a],id:a+1}))}};f.ua=function(a){(a=a.detail&&a.detail.id)&&(a=this.W[a-1])&&!C("frameexit",this,{url:a}).detail.handled&&window.open(a)};f.ya=function(){this.i||null==this.g||(C("framemouseout",this,{element:this.frames[this.g],id:1+this.g}),this.g=null)};
f.Aa=function(a){this.i||(a=Z(this,a),a!=this.g&&(null!=this.g&&C("framemouseout",this,{element:this.frames[this.g],id:1+this.g}),null!=a&&C("framemouseover",this,{element:this.frames[a],id:1+a}),this.g=a))};f.wa=function(a){this.i||(a=Z(this,a),a!=this.g&&(null!=this.g&&C("framemouseout",this,{element:this.frames[this.g],id:1+this.g}),null!=a&&C("framemouseover",this,{element:this.frames[a],id:1+a}),this.g=a))};
f.za=function(a){this.i&&a.target.classList.contains("frame")&&C("framemouseover",this,{element:a.target,id:1+this.frames.indexOf(a.target)})};f.xa=function(a){this.i&&a.target.classList.contains("frame")&&C("framemouseout",this,{element:a.target,id:1+this.frames.indexOf(a.target)})};f.ta=function(a){this.i&&a.target.classList.contains("frame")&&C("frametap",this,{element:a.target,id:1+this.frames.indexOf(a.target)})};
f.pa=function(){if(0<this.m&&0<this.b&&null!=this.a)return Math.max(1,this.a-Math.floor((this.m-1)/2)+1)};f.sa=function(){if(0<this.m&&0<this.b&&null!=this.a)return Math.min(this.b,this.a-Math.floor((this.m-1)/2)+this.m)};document.registerElement("gwd-swipegallery",{prototype:Q.prototype});}).call(this);
