repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: debug-statements
      - id: flake8
  - repo: https://github.com/asottile/reorder_python_imports
    rev: v1.3.4
    hooks:
      - id: reorder-python-imports
        language_version: python3.6
  - repo: https://github.com/asottile/pyupgrade
    rev: v1.10.1
    hooks:
      - id: pyupgrade

  - repo: https://github.com/ambv/black
    rev: 18.9b0
    hooks:
      - id: black
        args: [--safe]
        language_version: python3.7
  - repo: https://github.com/asottile/seed-isort-config
    rev: v1.3.0
    hooks:
      - id: seed-isort-config
        args: [--application-directories, "src:."]
  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v4.3.4
    hooks:
      - id: isort
