---
abstract: 'Create, Read, Update, Delete files, commits, issues, and web hooks on GitHub.'
author:
  - philiprbrenan@gmail.com
build_requires: {}
configure_requires:
  Module::Build: '0.4224'
dynamic_config: 1
generated_by: 'Module::Build version 0.4229, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: GitHub-Crud
provides:
  GitHub::Crud:
    file: lib/GitHub/Crud.pm
    version: '20201115'
requires:
  Carp: '0'
  Data::Dump: '0'
  Data::Table::Text: '20201029'
  Digest::SHA1: '0'
  Storable: '0'
  Test2::API: '0'
  Test::More: '0'
  Time::HiRes: '0'
  perl: v5.26.1
resources:
  bugtracker: https://github.com/philiprbrenan/GitHubCrud/issues
  license: http://dev.perl.org/licenses/
  repository: https://github.com/philiprbrenan/GitHubCrud
version: '20201115'
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
