matrix:
  include:
    - os: linux
      dist: xenial
      sudo: required
      language: python
      python: "3.7"

install:
  - python3 -m pip install flake8 flake8-pyi mypy

script:
  - python3 -m flake8
  - python3 -m pip install --no-deps .
  - python3 -m mypy examples
