language: python

matrix:
  include:
    - python: 2.7
    - python: 3.5
    - python: 3.6
    - python: 3.7
      dist: xenial
      sudo: true
    - python: 3.8
      dist: xenial
      sudo: true

addons:
  apt:
    sources:
      # https://bugreports.qt.io/browse/QTBUG-64928?focusedCommentId=389951&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-389951
      - sourceline: "deb http://us.archive.ubuntu.com/ubuntu/ xenial main universe"
    packages:
      - xvfb

install:
  - pip install tox
  - export TOX_ENV=`tox --listenvs | grep -v win | grep "py${TRAVIS_PYTHON_VERSION/./}" | tr '\n' ','`

script: tox -e $TOX_ENV
