dist: xenial
language: python
matrix:
  include:
    - python: 2.7
      env: TOXENV=py27-pytest2
    - python: 2.7
      env: TOXENV=py27-pytest3
    - python: 2.7
      env: TOXENV=py27-pytest4

    - python: 3.5
      env: TOXENV=py35-pytest2
    - python: 3.5
      env: TOXENV=py35-pytest3

    - python: 3.6
      env: TOXENV=py36-pytest2
    - python: 3.6
      env: TOXENV=py36-pytest3

    - python: 3.7
      env: TOXENV=py37-pytest2
    - python: 3.7
      env: TOXENV=py37-pytest3
    - python: 3.7
      env: TOXENV=py37-pytest4

    - python: 3.8
      env: TOXENV=py38-pytest2
    - python: 3.8
      env: TOXENV=py38-pytest3
    - python: 3.8
      env: TOXENV=py38-pytest4
install:
  - pip install -U tox
script:
  - tox --recreate
