repos:
-   repo: https://github.com/ambv/black
    rev: 19.10b0
    hooks:
    -   id: black
        args: [--safe, --quiet]
        language_version: python3
-   repo: https://github.com/asottile/blacken-docs
    rev: v0.2.0
    hooks:
    -   id: blacken-docs
        additional_dependencies: [black==18.6b4]
        language_version: python3
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v1.3.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: debug-statements
    -   id: flake8
-   repo: https://github.com/asottile/pyupgrade
    rev: v1.2.0
    hooks:
    - id: pyupgrade
-   repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.0.0
    hooks:
    -   id: rst-backticks
-   repo: local
    hooks:
    -   id: rst
        name: rst
        entry: rst-lint --encoding utf-8
        files: ^(CHANGELOG.rst|HOWTORELEASE.rst|README.rst)$
        language: python
        additional_dependencies: [pygments, restructuredtext_lint]
