language: python
matrix:
  include:
    - python: 3.5
      env: TOX_ENV=py35
    - python: 3.6
      env: TOX_ENV=py36
    - python: 3.7
      env: TOX_ENV=py37
      # TODO: the dist and sudo keys are currently needed to use Python 3.7.
      # They should be removed once Travis-CI supports 3.7 on the default image.
      dist: xenial
      sudo: true

install: pip install tox-travis coveralls

script: tox -e $TOX_ENV

after_success:
  - tox -e coverage-report
  - coveralls
