update: all
branch: master
schedule: "every two weeks"
pin: True
requirements:
  - requirements/python:
      updates: all
  - requirements/python-dev:
      updates: all
  - requirements/python-doc:
      updates: all
assignees:
  - deanmalmgren
