dist: xenial
language: python

python:
  - 3.6
  - 3.7
  - 3.8

before_install:
  # Clearing environment:
  - pip freeze | xargs pip uninstall -y
  # Installing poetry:
  - curl -sSL https://raw.githubusercontent.com/sdispater/poetry/master/get-poetry.py | python
  - source "$HOME/.poetry/env"
  # Installing tox runner for travis:
  - pip install tox-travis

script: tox

notifications:
  email:
    on_success: never
    on_failure: change
