sudo: false
language: python
python: "2.7"

matrix:
  include:
  - env: TOXENV=linters
  - env: TOXENV=py27-pytest39
  - env: TOXENV=py27-pytest310
  - env: TOXENV=py27-pytestlatest
  - env: TOXENV=py27-pytestlatest-xdist
  - env: TOXENV=py34-pytestlatest
    python: "3.4"
  - env: TOXENV=py35-pytestlatest
    python: "3.5"
  - env: TOXENV=py36-pytestlatest
    python: "3.6"
  - env: TOXENV=py27-pytestlatest-coveralls
install: pip install tox
# mysql_install_db will not work if it can't find the my-default.cnf file
before_script: sudo cp /etc/mysql/my.cnf /usr/share/mysql/my-default.cnf
script: tox
branches:
  except:
  - /^\d/
notifications:
  email:
  - bubenkoff@gmail.com
