pkg install binutils
pkg install ccls
pkg install clang
pkg install coreutils
pkg install cpio
pkg install cups
pkg install diffutils
pkg install dropbear
pkg install ghostscript
pkg install gzip
pkg install hunspell
pkg install libxkbcommon
pkg install llvm
pkg install lnd
pkg install lzip
pkg install mtools
pkg install nmh
pkg install openssh
pkg install plzip
pkg install polipo
pkg install rcm
pkg install rcs
pkg install renameutils
pkg install sc-im
pkg install tcl
pkg install termux-tools
pkg install texlive-bin
pkg install util-linux
pkg install xmlstarlet
pkg install xorg-xcalc
pkg install xorg-xclock
pkg install xrdp
pkg install xz-utils
