# Config file for automatic testing at travis-ci.org

language: python

matrix:
    include:
      - python: 2.7
        env: TOX_ENV=py27
      - python: 3.4
        env: TOX_ENV=py34
      - python: 3.5
        env: TOX_ENV=py35
      - python: 3.6
        env: TOX_ENV=py36
      - python: 3.7
        env: TOX_ENV=py37
        dist: xenial  # required for Python >= 3.7 (travis-ci/travis-ci#9069)
      - python: pypy
        env: TOX_ENV=pypy

install:
  - pip install tox

script:
  - tox -e $TOX_ENV

before_cache:
  - rm -rf $HOME/.cache/pip/log

cache:
  directories:
    - $HOME/.cache/pip
