language: python

jobs:
  include:
    - env: TOXENV=py27
      python: '2.7'
    - env: TOXENV=py35
      python: '3.5'
    - env: TOXENV=py36
      python: '3.6'
    - env: TOXENV=py37
      python: '3.7'
    - env: TOXENV=py38
      python: '3.8'
    - stage: deploy
      python: '3.8'
      install: pip install -U setuptools setuptools_scm
      script: skip
      deploy:
        provider: pypi
        user: nicoddemus
        distributions: sdist bdist_wheel
        skip_upload_docs: true
        password:
          secure: TfROFljW1ne09zgKkG1s9ggPscjcghWxW/KuoScjgzXQ6OBE7QNm4keLJZxq+dxYGwbON3hoFVzCq9bU4c5eyFAT+OEN7GRa+/WFXriZIilrWXsNWF1R+EEnIyjbNgFGXRX41XxQ0GzUNB+6xr8BexqTRgBp8gFdvoKulyibVWI=
        on:
          tags: true
          repo: pytest-dev/pytest-cpp

install:
 - sudo apt-get update
 - sudo apt-get install libboost-test-dev
 - wget https://github.com/google/googletest/archive/release-1.8.0.tar.gz
 - tar -zxvf release-1.8.0.tar.gz
 - "cd googletest-release-1.8.0/googletest && cmake . && sudo make install; cd -"
 - rm -rf googletest-release-1.8.0
 - pip install tox coveralls scons

script:
 - scons -j4 -C tests
 - tox

after_success:
  - coveralls
