language: python
python:
  - "3.7"
  - "3.6"
  - "3.5"
matrix:
  exclude:
    - python: "3.7"
    - python: "3.6"
    - python: "3.5"
  include:
    - python: "3.7"
      dist: xenial  # required for Python >= 3.7 (travis-ci/travis-ci#9069)
      env: TOXENV=flake8
    - python: "3.7"
      dist: xenial  # required for Python >= 3.7 (travis-ci/travis-ci#9069)
      env: TOXENV=sdist
    - python: "3.7"
      dist: xenial  # required for Python >= 3.7 (travis-ci/travis-ci#9069)
      env: TOXENV=py37
    - python: "3.6"
      env: TOXENV=py36
    - python: "3.5"
      env: TOXENV=py35
install:
  - pip install -r requirements-testing.txt
cache: pip
script:
  - tox
