[build-system]
requires = [
    "setuptools", "wheel",
    "cython>=0.24,<=0.29.14,!=0.27,!=0.27.2",
    'kivy_deps.gstreamer_dev~=0.2.0; sys_platform == "win32"',
    'kivy_deps.sdl2_dev~=0.2.0; sys_platform == "win32"',
    'kivy_deps.glew_dev~=0.2.0; sys_platform == "win32"',
    'kivy_deps.gstreamer~=0.2.0; sys_platform == "win32"',
    'kivy_deps.sdl2~=0.2.0; sys_platform == "win32"',
    'kivy_deps.glew~=0.2.0; sys_platform == "win32"',
]
