dist: trusty
sudo: required
services:
- postgresql
before_install:
- sudo apt-get -qq update
- sudo apt-get install -y yui-compressor node optipng
before_script:
- cp example.env .env
- psql -c 'create database pygame_test;' -U postgres
- psql pygame_test -c "CREATE USER pygame_test WITH PASSWORD 'password';" -U postgres
- psql pygame_test -c "GRANT ALL PRIVILEGES ON DATABASE pygame_test to pygame_test;"
  -U postgres
addons:
  postgresql: '9.6'
test:
  adapter: postgresql
  database: pygame_test
language: python
cache: pip
python:
- '3.6'
install:
- pip install --upgrade pip
- pip install -r requirements.dev.txt
- pip install --upgrade pytest
- pip install coveralls
- pip install -e .
script: APP_SECRET_KEY=a pytest
after_success:
- coveralls
before_deploy:
- pwd
- ls -la
- git checkout $TRAVIS_BRANCH
- pygameweb_release_version_correct
