matrix:
  include:
    - os: linux
      sudo: required
      dist: xenial
      language: python
      python: "2.7_with_system_site_packages"
      env: PACKAGES="xvfb gir1.2-gtk-3.0 python-gi python-gi-cairo python-flake8 python-pytest" PYTHON="python"
    - os: linux
      sudo: required
      dist: xenial
      language: python
      python: "3.5_with_system_site_packages"
      env: PACKAGES="xvfb gir1.2-gtk-3.0 python3-gi python3-gi-cairo python3-flake8 python3-pytest" PYTHON="python3"

install:
  - sudo apt-get update -q
  - sudo apt-get install --no-install-recommends -y $(echo $PACKAGES)

script:
  - xvfb-run -a "$PYTHON" -m pytest test.py
  - xvfb-run -a "$PYTHON" -m flake8
